pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sshagent (credentials: ['Azdigi-VPS-SSH']) {
                    sh 'ssh -o StrictHostKeyChecking=no root@116.118.49.239 \"cd /var/www/html/nvnhan0810.com && ./deploy/build.sh\"'
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent (credentials: ['Azdigi-VPS-SSH']) {
                    sh 'ssh -o StrictHostKeyChecking=no root@116.118.49.239 \"cd /var/www/html/nvnhan0810.com && php artisan optimize:clear && php artisan optimize\"'
                    sh 'ssh -o StrictHostKeyChecking=no root@116.118.49.239 \"cd /var/www/html/nvnhan0810.com &&  cp ./deploy/nginx.conf /etc/nginx/config.d/nvnhan0810.com.conf\"'
                    sh 'ssh -o StrictHostKeyChecking=no root@116.118.49.239 \"cd /var/www/html/nvnhan0810.com &&  nginx -t && sudo systemctl reload nginx\"'
                }
            }
        }
    }
}
